### ISSUE TITLE
Create student entity

### ISSUE THREAD

**Issue by rotespferd** [Dren-Tech/kennsla_api#12]
The student entity holds the data of a student, which reads pages and solves quizzes and co. A student can login into the frontend.

## ToDo
- [x] Add unit test
- [x] Add model file
- [ ] Add annotations for ORM
